#$ image build for docker hub

version: "3"
services:

  app:
    container_name: app
    build:
      context: .
      dockerfile: dockerfile
    image: raianedev/rinha_api:1.0
    volumes:
      - ./database/:/data/
    restart: always
