version: "3"
services:

  app:
    container_name: app
    image: golang:1.21
    volumes:
      - ./backend/:/go/src
      - ./database/:/data
    tty: true
    stdin_open: true
    restart: always
    environment:
      - SERVER_PORT=9999
      - DEBUG=debug
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "550MB"
    network_mode: host