## Docker compose for production

version: "3"
services:

  nginx:
    image : nginx:1.25-alpine
    depends_on:
      - app
      - app01
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9999:9999
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "50MB"
    network_mode: host

  app: &app
    hostname: app
    image: raianedev/rinha_api:1.0
    volumes:
      - ./database:/data
    environment:
      - SERVER_PORT=9990
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "250MB"
    network_mode: host

  app01: 
    <<: *app
    hostname: app01
    environment:
      - SERVER_PORT=9991