version: "3"
services:

  app:
    container_name: app
    image: golang:1.21
    volumes:
      - ./backend/:/go/src
      - ./database/:/data
    tty: true
    stdin_open: true
    restart: always
    network_mode: host

  sqlite3:
    container_name: sqlite3
    image: keinos/sqlite3:latest
    tty: true
    restart: always
    volumes:
      - ./database/:/data/
    network_mode: host
    command: [ "sqlite3", ".open /data/rinha_api.sqlite" ]
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "140MB"
